# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 21:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0068_worker_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerExperimentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdsourcing.Project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_configs', to='crowdsourcing.Worker')),
            ],
        ),
        migrations.AddField(
            model_name='templateitem',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
