# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 22:04
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0069_auto_20160303_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
