# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-04 21:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdsourcing', '0070_project_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='workerexperimentconfig',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
